[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
estimated_read_time = "1.0.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.113"
slugify-rs = "0.0.3"
ollama-rs = "0.1.6"
tabled = "0.15.0"
strum_macros = "0.26.1"
tokio = { version = "1.36.0", features = ["full"] }
convert_case = "0.6.0"
strum = "0.26.1"
